import {Router} from 'express';
const router = Router();
// import sendOtp  from '../controllers/sendOtp.js';
// import verifyOtp  from '../controllers/verifyOtp.js';
// import setMPIN from '../controllers/setMPIN.js';
// import loginUser from '../controllers/login.js';
// import upload from '../controllers/upload.js';
import  handleQuery  from '../controllers/handleQuery.js';
// import sendMessage from '../controllers/sendMessage.js';
// router.post('/otp',sendOtp);
// router.post('/verify',verifyOtp);
// router.post('/mpin',setMPIN);    
// router.post('/login',loginUser);
// router.post('/uploads',upload);
router.post('/query',handleQuery);
// router.post('/schemename',sendMessage);
export default router;